name: kk_stock
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.13
    - aiosignal==1.3.2
    - akracer==0.0.13
    - annotated-types==0.7.0
    - anyio==4.9.0
    - attrs==25.3.0
    - beautifulsoup4==4.13.4
    - certifi==2025.6.15
    - charset-normalizer==3.4.2
    - click==8.2.1
    - decorator==5.2.1
    - dnspython==2.7.0
    - et_xmlfile==2.0.0
    - fastapi==0.115.13
    - frozenlist==1.7.0
    - h11==0.16.0
    - html5lib==1.1
    - httptools==0.6.4
    - idna==3.10
    - jsonpath==0.82.2
    - lxml==5.4.0
    - multidict==6.5.0
    - nest-asyncio==1.6.0
    - numpy==2.3.0
    - openpyxl==3.1.5
    - pandas==2.3.0
    - propcache==0.3.2
    - py-mini-racer==0.6.0
    - pydantic==2.11.7
    - pydantic_core==2.33.2
    - PyJWT==2.10.1
    - pymongo==4.13.2
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.0
    - pytz==2025.2
    - PyYAML==6.0.2
    - requests==2.32.4
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.7
    - starlette==0.46.2
    - tabulate==0.9.0
    - tqdm==4.67.1
    - typing-inspection==0.4.1
    - typing_extensions==4.14.0
    - tzdata==2025.2
    - urllib3==2.5.0
    - uvicorn==0.34.3
    - uvloop==0.21.0
    - watchfiles==1.1.0
    - webencodings==0.5.1
    - websockets==15.0.1
    - xlrd==2.0.2
    - yarl==1.20.1
    - scipy==1.15.3
    - pypinyin==0.54.0
    - matplotlib==3.8.4
    - mplfinance>=0.12.10
    - agno>=0.7.0
    - anthropic>=0.40.0
    - openai>=1.0.0
    - langgraph>=0.2.50
    - langchain>=0.3.0
    - langchain-community>=0.3.0
    - langsmith>=0.2.0
    - transformers>=4.45.0
    - scikit-learn>=1.3.0
    - joblib>=1.3.0
    - xgboost>=2.0.0
    - plotly>=5.0.0
    - seaborn>=0.12.0
    - pyecharts>=2.0.0
    - wordcloud>=1.9.0
    - Pillow>=10.0.0
    - celery>=5.3.0
    - redis>=5.0.0
    - tencentcloud-sdk-python>=3.0.0
    - schedule>=1.2.0
    - tushare>=1.2.89
    - akshare>=1.17.0
    - passlib>=1.7.4
    - abupy==0.4.0